services:
  - docker
notifications:
  email: false
language: node_js
node_js: '10'
cache: npm
os: linux
before_install:
  - docker pull park64kr/gruut-nodejs:latest
  - docker run --name gruut-service-endpoint -e MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD -d park64kr/gruut-nodejs:latest
install:
script:
  - docker exec gruut-service-endpoint sh -c "
    mkdir -p workspace && cd workspace;
    git clone --depth=5 --branch=$TRAVIS_BRANCH https://github.com/gruut/enterprise-service-endpoint.git && cd enterprise-service-endpoint;
    npm install;
    npm run lint;
    sequelize db:create;
    sequelize db:migrate;
    npm run test;
    "
